# Generated by Django 2.0.5 on 2018-05-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychotype',
            name='psychotype',
            field=models.ManyToManyField(to='core.Speciality'),
        ),
    ]
