# Generated by Django 2.0.5 on 2018-05-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_psychotype_psychotype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychotype',
            old_name='psychotype',
            new_name='speciality',
        ),
        migrations.AddField(
            model_name='subject',
            name='speciality',
            field=models.ManyToManyField(to='core.Speciality'),
        ),
    ]
