# Generated by Django 2.0.5 on 2018-06-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180531_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='university',
            field=models.ManyToManyField(to='core.University'),
        ),
    ]
